Hi Team 

 Please find the exceptions as mentioned below

=================== Exceptions List =====================================

Exception : 1 
 2017-10-10_05:39:46.393 [ajp-nio-9692-exec-7] INFO  cvisLogger - ZYMETEST/shshetty:COMPLIANCESCORE MasterData is Started User is: shshetty
 2017-10-10_05:39:47.603 [ajp-nio-9692-exec-7] INFO  cvisLogger - ZYMETEST/shshetty:batchId: 0 batchStartTime: Tue Oct 10 05:39:47 CDT 2017
 2017-10-10_05:35:31.344 [ajp-nio-9692-exec-5] INFO  cvisLogger - User: shshetty has choosen the Client :: ZYMETEST
 2017-10-10_05:36:37.856 [ajp-nio-9692-exec-9] INFO  cvisLogger - File Upload done
 2017-10-10_05:36:38.922 [ajp-nio-9692-exec-9] INFO  cvisLogger - ZYMETEST/shshetty:TIMELINESSTRACKER MasterData is Started User is: shshetty
 2017-10-10_05:36:41.582 [ajp-nio-9692-exec-9] INFO  cvisLogger - ZYMETEST/shshetty:TIMELINESSTRACKER MasterData is loaded BathchId: 13 TemplateName: TimelinessTracker Totaltime: 2 seconds
 2017-10-10_05:36:42.795 [ajp-nio-9692-exec-9] INFO  cvisLogger - Notify Message For Master Data Load:{"batchId":13,"attributes":null,"fileName":"13-Timeliness_master_ZYMETEST.xls","status":"SUCCESS","clientName":"ZYMETEST","masterData":"TIMELINESS TRACKER","uploadMethod":"Manual"}
 2017-10-10_05:39:45.550 [ajp-nio-9692-exec-7] INFO  cvisLogger - File Upload done
 2017-10-10_05:39:46.393 [ajp-nio-9692-exec-7] INFO  cvisLogger - ZYMETEST/shshetty:COMPLIANCESCORE MasterData is Started User is: shshetty
 2017-10-10_05:39:47.603 [ajp-nio-9692-exec-7] INFO  cvisLogger - ZYMETEST/shshetty:batchId: 0 batchStartTime: Tue Oct 10 05:39:47 CDT 2017
2017-10-10_05:39:47.771 [ajp-nio-9692-exec-7] ERROR cvisLogger - ZYMETEST/shshetty:ComplianceScoreDataHandler : org.springframework.dao.DuplicateKeyException: SqlMapClient operation; SQL []; Duplicate entry '2' for key 'PRIMARY'; nested exception is java.sql.BatchUpdateException: Duplicate entry '2' for key 'PRIMARY'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:206)
        at com.zyme.core.services.productionTracking.impl.dao.ibatis.IbatisComplianceScoreAccessor.addComplianceScore(IbatisComplianceScoreAccessor.java:37)
        at com.zyme.core.services.productionTracking.impl.ComplianceScoreManagementServiceImpl.addComplianceScore(ComplianceScoreManagementServiceImpl.java:155)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invoke(ThrowsAdviceInterceptor.java:125)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

====================== End of Exception 1 =================================================

Exception : 2 
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
          at java.lang.Thread.run(Thread.java:745)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
          at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Duplicate entry '2' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1582)
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1248)
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
        at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
        at sun.reflect.GeneratedMethodAccessor2214.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibatis.common.jdbc.logging.PreparedStatementLogProxy.invoke(PreparedStatementLogProxy.java:88)
        at com.sun.proxy.$Proxy106.executeBatch(Unknown Source)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor$Batch.executeBatch(SqlExecutor.java:608)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeBatch(SqlExecutor.java:119)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.executeBatch(SqlMapExecutorDelegate.java:807)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.executeBatch(SqlMapSessionImpl.java:184)

====================== End of Exception 2 =================================================

Exception : 3 
               at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
         ... 102 more
         at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
         ... 102 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1543)
        ... 116 more

2017-10-10_05:39:49.362 [ajp-nio-9692-exec-7] INFO  cvisLogger - ZYMETEST/shshetty:COMPLIANCESCORE MasterData is loaded BathchId: 14 TemplateName: ComplianceScore Totaltime: 2 seconds

====================== End of Exception 3 =================================================

Exception : 4 
          2017-10-10_05:39:49.409 [ajp-nio-9692-exec-7] ERROR cvisLogger - SingleStepLoadAction excecutejava.lang.RuntimeException: org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
        at com.zyme.ChannelInv.coreservlets.DataLoad.SingleStepLoadAction.loadNonChannelData(SingleStepLoadAction.java:143)
        at sun.reflect.GeneratedMethodAccessor4550.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:270)
        at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:187)
        at org.apache.struts.actions.LookupDispatchAction.execute(LookupDispatchAction.java:150)
        at com.zyme.ChannelInv.coreservlets.DataLoad.SingleStepLoadAction.execute(SingleStepLoadAction.java:87)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:236)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
        at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.displaytag.filter.ResponseOverrideFilter.doFilter(ResponseOverrideFilter.java:125)

====================== End of Exception 4 =================================================
